### ISSUE TITLE
Add auto-achive script

### ISSUE THREAD

**Issue by jason-neal** [jason-neal/parchive#1]
Scheduled process that
- Gets current  Sweet-cat and exoEU databases.
- Organizes the files and correctly names with date.
- Adds/commits/pushes the change to the repo.

**Comment by DanielAndreasen** [comment]
Might not be the best solution, but you can add a cronjob that does this.

**Comment by jason-neal** [comment]
Thats what I was thinking, just have not done it.

**Comment by jason-neal** [comment]
Have created a script the does the automatic updating and committing. (it is a bit of a hack but works)
Need to run it from repo's root directory.
